name: engineio

on: [push]

jobs:
  ubuntu-18_04:
    name: ubuntu-18_04
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1

      - name: Make build.cmd executable
        run: chmod +x ./build.cmd

      - name: Run './build.cmd Ci'
        run: ./build.cmd Ci
