name: engineio

on: [push]

jobs:
  ubuntu-latest:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run './build.cmd Ci'
        run: ./build.cmd Ci
      - uses: actions/upload-artifact@v1
        with:
          name: output
          path: output
